First version of column streaming for differential assembly
ratschlab/metagraph pull request #426
Opened 2022-08-09 16:11 UTC by hmusta

2022-08-26 09:40 UTC, karasikov commented
Is this ready for review?

2022-08-26 10:18 UTC, hmusta commented
> Is this ready for review?

Yes

2022-08-31 10:43 UTC, karasikov requested changes

2022-08-31 10:43 UTC, karasikov commented on metagraph/src/graph/annotated_dbg.hpp
> +    const std::shared_ptr<Annotator> annotator_;
Will it work if you pass lazy annotator to AnnotatedDBG? This points to a design issue.
Maybe it's better to do without AnnotatedDBG in differential assembly? Better pass graph and annotation separately. Then you can pass lazy annotation in any type you want.

2024-06-11 09:16 UTC, hmusta commented
Superseded by #487

2024-06-11 09:16 UTC, closed without merging